services:
  # Our Postgres database
  db: # The service will be named db.
    image: postgres:16-alpine
    restart: always # Always try to restart if this stops running
    environment: # Provide environment variables
      POSTGRES_USER: baloo # POSTGRES_USER env var w/ value baloo
      POSTGRES_PASSWORD: junglebook
      POSTGRES_DB: lenslocked
    ports: # Expose ports so that apps not running via docker compose can connect to them.
      - 5555:5432 # format here is "port on our machine":"port on container"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Adminer provides a nice little web UI to connect to databases
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: win98 # Pick a theme - https://github.com/vrana/adminer/tree/master/designs
    ports:
      - 3333:8080
volumes:
  pgdata:
